version: "3.7"

services:
  trashly:
    image: localhost:5000/trashly
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.labels.category == main]
    networks:
        - gema

networks:
  gema:
    external: true
